# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cff4881e7faa518e5b813bfc11e37cacc8c8a73b5981d0f89ea8f02ecd7da5446586fed5d01d43a6359e7422a08ea139ffdf858f30033bfc8788e7bf12e2d30

test:
  secret_key_base: 1123da0f3ef6c32a0bdb0011ae0876c0085e1532d4f8a572851088bc776ecba082402f94803a1eb516e40417397a47bf40bfc31b5bb1b91d8ad072db1d7b30f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
